name: Feature request
description: Suggest a new feature
labels: ["enhancement"]
type: "Feature"
title: "[FEATURE] "
body:
    - type: markdown
      attributes:
          value: |
              **NOTE**: Please write in **English**.

              > [!IMPORTANT]
              > If you're requesting a feature that pertains to the shell itself (bar, dashboard, launcher, etc) rather than the dotfiles, please create a feature request in the [shell repo](https://github.com/caelestia-dots/shell/issues) instead.

    - type: textarea
      attributes:
          label: "What would you like to be added?"
          description: "Can be a suggestion for an existing feature. You can suggest a widget, minor user interaction changes.. whatever."

    - type: textarea
      attributes:
          label: "How will it help?"
          description: "It's helpful to include examples (like in your use case)."

    - type: textarea
      attributes:
          label: "Extra info"
          description: "If you want a new widget, a pic of the inspiration (if available) would be awesome."
