name: Issue
description: Report an issue with the dots
labels: ["bug"]
type: "Bug"
title: "[BUG] "
body:
    - type: markdown
      attributes:
          value: |
              **Welcome to submitting a new issue!**
              - It takes only a few steps, so please be patient and read through everything :)
              - **Tip**: If your issue is not a feature request and is not an issue with the dots (e.g. "how do I use X feature"), please use [Discussions](https://github.com/caelestia-dots/shell/discussions) instead.

              > [!IMPORTANT]
              > If your issue pertains to the shell itself (bar, dashboard, launcher, etc) rather than the dotfiles, please create an issue for the [shell repo](https://github.com/caelestia-dots/shell/issues) instead.
    - type: checkboxes
      attributes:
          label: "1. Before you submit"
          description: "Hint: The 2nd and 3rd boxes are **not** forcibly required as you may have been unable to do so."
          options:
              - label: I have read the above instructions and am sure that this is supposed to be posted here.
                required: true
              - label: I've successfully updated to the latest versions following the [updating guide](https://github.com/caelestia-dots/caelestia?tab=readme-ov-file#updating).
                required: false # Not required since user may have failed to do so
              - label: I've successfully updated the system packages to the latest.
                required: false # Not required since user may have failed to do so
              - label: I've ticked the checkboxes without reading their contents
                required: false # Obviously

    - type: textarea
      attributes:
          label: "2. Version info"
          description: "Run `caelestia -v` and paste the result below."
          placeholder: "Paste the output of `caelestia -v` here!"
          render: text
      validations:
          required: true

    - type: textarea
      attributes:
          label: "3. Describe the issue"
          placeholder: "Describe your issue here!"
      validations:
          required: true

    - type: textarea
      attributes:
          label: "4. Logs content"
          description: |
              **Tips for pasting logs:**
              1. Use `LANG=C LC_ALL=C` to get the output of a command in English.
                 - For example, `LANG=C LC_ALL=C date` displays the current date and time in English.
              2. If it throws errors, **PLEASE**, attach logs and describe in detail if possible.
                 - Installation failed? Run installation again for logs.
                 - You may use more code blocks when needed.
              3. In case you are confused, `<details>` and `<summary>` are HTML tags for folding the (typically very long) logs inside. Please do not touch them (unless you know what you are doing).
              4. If the logs are suuuuuuper long, consider using an online pastebin service instead (e.g., https://pastes.dev/).
          value: |
              <details><summary>Logs</summary>

              ```
              <!-- Put your log content here!-->
              ```

              </details>
          render: text
      validations:
          required: false # Logs may not be available

    - type: checkboxes
      attributes:
          label: Reminder
          options:
              - label: I agree that it's usually impossible for others to help me without my logs.
                required: true
